# MSN-AI - Docker Compose Configuration
# Version: 1.0.0
# Author: Alan Mac-Arthur García Díaz
# License: GNU General Public License v3.0
# Description: Complete MSN-AI stack with Ollama AI service

services:
  # MSN-AI Web Application
  msn-ai:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: msn-ai-app
    ports:
      - "${MSN_AI_PORT:-8000}:8000"
    environment:
      - MSN_AI_VERSION=2.1.0
      - OLLAMA_HOST=ollama:11434
      - MSN_AI_PORT=8000
      - PYTHONUNBUFFERED=1
    volumes:
      - msn-ai-data:/app/data
      - msn-ai-chats:/app/data/chats
      - msn-ai-logs:/app/data/logs
    depends_on:
      ollama:
        condition: service_started
      ai-setup:
        condition: service_completed_successfully
    networks:
      - msn-ai-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/app/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    labels:
      - "com.msnai.service=web"
      - "com.msnai.version=2.1.0"
      - "com.msnai.author=alan.mac.arthur.garcia.diaz@gmail.com"

  # Ollama AI Service
  ollama:
    image: ollama/ollama:latest
    container_name: msn-ai-ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_ORIGINS="*"
    volumes:
      - ollama-data:/root/.ollama
      - ./scripts/:/scripts:ro
    networks:
      - msn-ai-network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "sh",
          "-c",
          "curl -f http://localhost:11434/ && curl -f http://localhost:11434/api/tags",
        ]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 60s
    labels:
      - "com.msnai.service=ai"
      - "com.msnai.version=2.1.0"
    # GPU support (uncomment if you have NVIDIA GPU)
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  # Hardware Detection & Model Setup Service
  ai-setup:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: msn-ai-setup
    environment:
      - OLLAMA_HOST=ollama:11434
      - SETUP_TIMEOUT=300
      - MAX_RETRIES=10
    volumes:
      - ollama-data:/root/.ollama
      - ./scripts/:/scripts:rw
      - msn-ai-data:/app/data
    networks:
      - msn-ai-network
    depends_on:
      ollama:
        condition: service_started
    command: ["/app/docker/scripts/ai-setup-docker.sh"]
    restart: "no"
    labels:
      - "com.msnai.service=setup"
      - "com.msnai.version=2.1.0"

# Networks
networks:
  msn-ai-network:
    driver: bridge
    name: msn-ai-network
    labels:
      - "com.msnai.network=main"

# Volumes for data persistence
volumes:
  # MSN-AI application data
  msn-ai-data:
    name: msn-ai-data
    labels:
      - "com.msnai.volume=app-data"

  # Chat history persistence
  msn-ai-chats:
    name: msn-ai-chats
    labels:
      - "com.msnai.volume=chats"

  # Application logs
  msn-ai-logs:
    name: msn-ai-logs
    labels:
      - "com.msnai.volume=logs"

  # Ollama models and data
  ollama-data:
    name: msn-ai-ollama-data
    labels:
      - "com.msnai.volume=ollama-data"
